### ISSUE TITLE
Could you add explanation.

### ISSUE THREAD

**Issue by IAmAnubhavSaini** [anitasv/zoom#1]
I ran application on mobile and looked at the code on mobile too. I am scratching my head at mathematics. Could you please add explain mathematics, js and css behind it? 

Maybe a blog post or in readme file.

**Comment by anitasv** [comment]
Certainly, I'll see what I can do. A hint might be a transformation is Ax + b, where A is a matrix, and b is a vector. I probably didn't make that clear.

**Comment by developit** [comment]
Would be good to mention the implied jQuery dependency.

**Comment by anitasv** [comment]
Oops, I thought I did, but it is something interested people can remove easily.

**Comment by eshacker** [comment]
My two cents: What's easy and implied for you might be very difficult for others to understand.

**Comment by anitasv** [comment]
https://github.com/anitasv/zoom/wiki/Explaining-Math

**Comment by anitasv** [comment]
I have also removed jquery dependency.
