### ISSUE TITLE
select multiple IDs

### ISSUE THREAD

**Issue by YellowLabIT** [anitasv/zoom#13]
Hello, i've just tried many ways but i can't figure out how to select multiple ids...
like this way
`var el = document.getElementById('zoom_' + (i+1));
var zm = new Zoom(el, {
    pan: true,
    rotate: false
});`
another 
`var el = document.querySelectorAll('#zoom_1, #zoom_2, #zoom_3' );
           ...`
also i've just tried with class
`var el = document.getElementsByClassName('image');
        ...`
also created a for loop, but probably i'm not a javascript genius...
someone can give me a little help?
thankyou :)

**Comment by anitasv** [comment]
What are you trying to do? You can pass any element to Zoom constructor it will make it zoomable.

**Comment by YellowLabIT** [comment]
i've a image gallery and want to zoom all images... for a single image it works perfectly, also if i duplicate the code many times changing the id (zoom_1) (zoom_2) etc...

**Comment by anitasv** [comment]
You can write a for loop to do it right?
var imgs = document. getElementsByClassName('zoomable');
for (var img in imgs) {
  new Zoom(img);
}

**Comment by YellowLabIT** [comment]
thankyou for your time... all works fine.
