### ISSUE TITLE
is it possible set zoom by js code and fix it?

### ISSUE THREAD

**Issue by peratik** [anitasv/zoom#17]
Hello

I want to change zoom of a div by this library and fix it (no zoom , no pan, no rotate), Is it possible something like this:

```
		var zm = new Zoom(elem, {
			zoom:false,
			pan: false,
			rotate: false
		});	
		zm.zoom(x);
```

**Comment by anitasv** [comment]
You can simply use css scale right?

**Comment by peratik** [comment]
Yes.
