### ISSUE TITLE
Version on NPM not updated to 1.0.7

### ISSUE THREAD

**Issue by JaapBarnhoorn** [anitasv/zoom#27]
Hi,

The version of zoom I'm getting when npm installing is 1.0.6.
This version does not contain the `247 - for (k in cfg_def) {` -> `for (var k in cfg_def) {`.
Thus it's not working in TypeScript

Could this be fixed?

**Comment by anitasv** [comment]
Sure, send me a pull request.

**Comment by JaapBarnhoorn** [comment]
The repository already has the fix, the only thing that is left to do is update the version on npm to 1.0.7...

**Comment by nickells** [comment]
+1 I am needing your latest bug fixes in my app and would love to update it via npm vs some dirty copy+paste, or forking my own…

**Comment by anitasv** [comment]
On it!

**Comment by anitasv** [comment]
Done, let me know if it works for you now.
