### ISSUE TITLE
Zoom element to be panned with touchmove on another element?

### ISSUE THREAD

**Issue by danavangard** [anitasv/zoom#33]
This Zoom project is awesome, and I am using it for prototyping in my project. I wish to implement a feature where I can touchmove on a 100px X 100px div that activates panning of a div/image container attached to the Zoom function. There is so much brilliant math in your code that I haven't the slightest brilliant clue where to start, lol.

So I was wondering, is the following piece of code enough to modify for my needs? I only need to touchmove (for panning of element) with one finger only on the 100px X 100px div, with the last touchmove (perhaps on touchend) position of panned element being used as touchstart coordinates before touchmove is used again :

```
var getCoordsSingle = function(t) {
        var oX = elem.offsetLeft;
        var oY = elem.offsetTop;
        var x = t[0].pageX - oX;
        var y = t[0].pageY - oY;
        return [
            [x, y],
            [x + 1, y + 1]
        ];
    }; 
```
It would be awesome if you could guide me in modifying your code or any other part of code so I could get this feature to work. I am basically implementing a "turbo" option for tablets where a simple slide of the thumb on the small div would pan the element attached to the zoom function in any direction the thumb is sliding, regardless of zoom applied to the attached element. Of course, the speed of the panning would be governed by a variable I could change. I have already implemented these features on some other pan/zoom code designed for desktop/mouse using matrix values, and tried to port them onto your code, but because of code design, nothing works as expected so far.

Any help really appreciated. Thx for awesome project.
dan

UPDATE Feb 12, 2020

Ok, found a solution that does not require a separate div.

**Comment by danavangard** [comment]
Found a solution that doesn't require separate div. Simply added a factor for faster zoom while using only one-finger touch:

```
var getCoordsSingle = function(t){
        var oX = elem.offsetLeft;
        var oY = elem.offsetTop;
        var x = (t[0].pageX - oX) * 12; // Factor for faster pan, the higher the further the panning.
        var y = (t[0].pageY - oY) * 12;
. . .
```
Seems simple enough but this way the thumb doesn't need to travel more than a centimeter while holding an iPad with two hands in order to pan the element. And when using two fingers however, the panning length/speed returns to its default, which allows more precise panning while rotating.

**Comment by anitasv** [comment]
Glad it works, my thought process was finger should map to previous and current positions. It makes sense one may need faster zooms.
