### ISSUE TITLE
Configurability

### ISSUE THREAD

**Issue by sandstrom** [anitasv/zoom#6]
This is a great library! ⛵️ 

I'd like to configure it to only (1) pinch-zoom, (2) drag-pane (within the zoomed area) and (3) double-tap to reset, but without rotations.

Is there any plans to add options for rotations/moving?

```js
let myZoom = Zoom(myEl, { rotate: false });
```

**Comment by anitasv** [comment]
double tap to reset should have worked, is it broken?

**Comment by anitasv** [comment]
Check this link: http://anitasv.github.io/zoom/

Disabling rotation is frequently asked, I will add it.

**Comment by sandstrom** [comment]
@anitasv Awesome!

Double-tap to reset worked perfectly, it was just en example of what may be configurable (just an idea). Disabling rotation would be great! ⛵️

**Comment by anitasv** [comment]
Pan support: 

http://anitasv.github.io/zoom/zoom_pan.html

**Comment by anitasv** [comment]
https://github.com/anitasv/zoom/pull/7/files

**Comment by anitasv** [comment]
Introduced a bug during the change; so update if you are seeing some issues: https://github.com/anitasv/zoom/pull/8/files
