### ISSUE TITLE
After rotate, pan is broken

### ISSUE THREAD

**Issue by ghochee** [anitasv/zoom#9]
Example

1. Rotate image about 45°
2. Lift fingers
3. Pan vertically down

Expect: rotated image to pan down (-90°)
Result: image pans along -45°

It is panning "down" in the reference frame of the image when it should be panning in the reference frame of the canvas.

**Comment by anitasv** [comment]
Thanks, I just added pan two days ago :(. Fixing.

**Comment by anitasv** [comment]
Issue happened during state management fix, pull request:

https://github.com/anitasv/zoom/pull/10

**Comment by anitasv** [comment]
Fix demo available; npm publish complete. links update pending.

**Comment by anitasv** [comment]
Demo working again: anitasv.github.io/zoom/

**Comment by ghochee** [comment]
Looks cool. Also I am glad the fix was *committed through pushed* faster than it took me to type the bug report. Next time it will be something NP hard.

**Comment by anitasv** [comment]
That was because it was working fine; and was broken due to last commit. Even for successive rotations it was broken. Just order of applying transformations went wrong. Thanks for the bug report.
